import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen flex items-center justify-center'>
        <form className='bg-white flex rounded-lg w-1/2 font-latoRegular'>
          <div className='flex-1 text-gray-700 p-20'>
            <h1 className='text-3xl pb-2 font-latoBold'>Let's get started 👋</h1>
            <p className='text-lg text-gray-500'>Join our e-learning platform and unlock over 500+ courses
              and digital assets ready to download.
            </p>
            <div className='mt-6'>
              <div className='pb-4'>
                <label htmlFor="name">Name</label>
                <input type="text" name="name" placeholder='Enter your name'/>
              </div>
            </div>
          </div>
        </form>
      </main>

    </div>
  );
}
